#!/bin/sh
#
# unit test functions
#

##
# Executes a single test against a single function using a single table.
#
# @param $1 Detox Executable
# @param $2 Input Filename
# @param $3 Output Filename
# @param $4 Method (utf_8, safe, etc)
# @param $5 Table (path to the table to use)
#
# @return int 0 for success, 1 for failure
#
function test_single_table ()
{
	if [ -z "$1" -o -z "$2" -o -z "$3" -o -z "$4" -o -z "$5" ] ; then
		echo missing parameters
		return 1
	fi

	DETOX=$1
	INPUT=$2
	OUTPUT=$3
	METHOD=$4
	TABLE=$5

	if [ ! -x "$DETOX" ] ; then
		echo $DETOX is not executable
		return 1
	fi

	if [ ! -f "$TABLE" ] ; then
		echo $TABLE is not a file
		return 1
	fi

	BASE=/tmp/detoxtest/
	if [ ! -d $BASE ] ; then
		mkdir $BASE
	fi
	WORK=$(realpath $(mktemp -d $BASE/test-XXXXXX))

	TMPTABLE=$WORK/test.tbl
	cp $TABLE $TMPTABLE

	SEQUENCE=unittest
	RC=$WORK/detoxrc

	cat <<- DONE > $RC
	sequence $SEQUENCE {
		$METHOD {
			filename "$TMPTABLE";
		};
	};
	DONE

	cd $WORK

	touch "$INPUT"
	$DETOX -v -s $SEQUENCE -f $RC "$INPUT"
	if [ ! -f "$OUTPUT" ] ; then
		echo expected output not found
		return 1
	fi

	return 0	
}
